# Generated by Django 5.1.3 on 2024-11-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sermon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='written_sermon_url',
        ),
        migrations.AddField(
            model_name='sermon',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='sermon_documents/'),
        ),
    ]
